[package]
name = "testing"
version = "0.1.0"
edition = "2024"

[dependencies]
file_system = { workspace = true }
users = { workspace = true }
time = { workspace = true }
virtual_file_system = { workspace = true }
task = { workspace = true }
log = { workspace = true }
graphics = { workspace = true }
little_fs = { workspace = true }
authentication = { workspace = true }
drivers_native = { workspace = true }
drivers_core = { workspace = true }
drivers_shared = { workspace = true }
drivers_std = { workspace = true }
executable = { workspace = true }
abi_definitions = { workspace = true }
network = { workspace = true }
