[package]
name = "command_line_shell"
version = "0.1.0"
edition = "2024"

[dependencies]
xila = { path = "../../../", features = ["host"] }
getargs = { version = "0.5" }

[target.'cfg(any(target_os = "linux", target_os = "macos", target_os = "windows"))'.dev-dependencies]
drivers_native = { workspace = true }
drivers_core = { workspace = true }
drivers_shared = { workspace = true }
drivers_std = { workspace = true }
time = { workspace = true }
little_fs = { workspace = true }
testing = { workspace = true }

[[test]]
name = "integration_test"
path = "tests/integration_test.rs"
