[package]
name = "abi_definitions"
version = "0.1.0"
edition = "2024"

[dependencies]
virtual_file_system = { workspace = true }
file_system = { workspace = true }
task = { workspace = true }
time = { workspace = true }
memory = { workspace = true }
network = { workspace = true }
synchronization = { workspace = true }

log = { workspace = true }
abi_context = { workspace = true }

[features]
default = []
allocation_redundancy_check = []

[dev-dependencies]
drivers_native = { workspace = true }
drivers_core = { workspace = true }
drivers_shared = { workspace = true }
drivers_std = { workspace = true }
little_fs = { workspace = true }
users = { workspace = true }
