[package]
name = "virtual_file_system"
version = "0.1.0"
edition = "2024"

[dependencies]
file_system = { workspace = true }
task = { workspace = true }
users = { workspace = true }
time = { workspace = true }
network = { workspace = true }
synchronization = { workspace = true }
shared = { workspace = true }
log = { workspace = true }

embedded-io-async = { workspace = true }

[dev-dependencies]
drivers_native = { workspace = true }
drivers_core = { workspace = true }
drivers_shared = { workspace = true }
drivers_std = { workspace = true }
little_fs = { workspace = true }
abi_definitions = { workspace = true }

[[test]]
name = "integration"
path = "tests/integration.rs"
