[package]
name = "abi_context"
version = "0.1.0"
edition = "2024"

[dependencies]
task = { workspace = true }
futures = { workspace = true }
synchronization = { workspace = true }
file_system = { workspace = true }
log = { workspace = true }
smol_str = { workspace = true }
virtual_file_system = { workspace = true }

[dev-dependencies]
drivers_core = { workspace = true }
drivers_std = { workspace = true }
drivers_shared = { workspace = true }
drivers_native = { workspace = true }
