[package]
name = "internationalization_macros"
version = "0.1.0"
edition = "2024"

[dependencies]
syn = { workspace = true }
quote = { workspace = true }
proc-macro2 = { workspace = true }
regex = { workspace = true }
once_cell = "1.21"
serde_json = "1.0"

[lib]
proc-macro = true
